allowed:
    domains: http://localhost:8080/login,http://localhost:3000/login,https://localhost:3000/login
logging:
    level:
        org:
            springframework:
                security: INFO
security:
    user:
        password: password
server:
    contextPath: /uaa
    port: 9999
spring:
    profiles:
        active: ${activeProfile}
